# Generated by Django 4.1.5 on 2023-01-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Uttora", "Uttora"),
                            ("Gulshan", "Gulshan"),
                            ("Dhanmondi", "Dhanmondi"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gender", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="profile_images"),
                ),
                ("rdoc", models.FileField(blank=True, upload_to="rdocs")),
            ],
        ),
    ]
